import { describe, expect, it } from 'vitest';
import { buildPatternCompilePlan, listPatterns } from '../sdk/src/index.js';

describe('pattern manifest scaffold', () => {
  it('exposes the first core entries and marks Ownable as scaffolded', () => {
    const patterns = listPatterns();
    expect(patterns.length).toBeGreaterThan(0);
    expect(patterns[0]?.id).toBe('core.ownable');
    expect(patterns[0]?.status).toBe('scaffolded');
    expect(patterns[0]?.contractPath).toBe('contracts/core/ownable.sil');
    expect(patterns[0]?.docPath).toBe('docs/patterns/core/ownable.md');
    expect(patterns[0]?.verification.compileValidated).toBe(true);
    expect(patterns[0]?.verification.runtimeValidated).toBe(true);
    expect(patterns[0]?.verification.auditStatus).toBe('internal-regression-gated');
    expect(patterns[0]?.compiler.requiresPatchedSilverc).toBe(false);
    expect(patterns[0]?.compiler.bootstrapCommand).toBe('npm run bootstrap:silverc');
    expect(patterns[1]?.id).toBe('core.multisig');
    expect(patterns[1]?.status).toBe('scaffolded');
    expect(patterns[2]?.id).toBe('core.timelock');
    expect(patterns[2]?.status).toBe('scaffolded');
    expect(patterns[3]?.id).toBe('core.vault');
    expect(patterns[3]?.status).toBe('scaffolded');
    expect(patterns[4]?.id).toBe('core.escrow-bilateral');
    expect(patterns[4]?.status).toBe('scaffolded');
    expect(patterns[5]?.id).toBe('core.escrow-milestone');
    expect(patterns[5]?.status).toBe('scaffolded');
    expect(patterns[6]?.id).toBe('core.streaming-payment');
    expect(patterns[6]?.status).toBe('scaffolded');
    expect(patterns[7]?.id).toBe('core.vesting');
    expect(patterns[7]?.status).toBe('scaffolded');
    expect(patterns[8]?.id).toBe('core.dead-mans-switch');
    expect(patterns[8]?.status).toBe('scaffolded');
    expect(patterns[9]?.id).toBe('core.social-recovery');
    expect(patterns[9]?.status).toBe('scaffolded');
    expect(patterns[10]?.id).toBe('core.atomic-swap-htlc');
    expect(patterns[10]?.status).toBe('scaffolded');
    expect(patterns[11]?.id).toBe('core.freelance-payroll');
    expect(patterns[11]?.status).toBe('scaffolded');
    expect(patterns[12]?.id).toBe('krc20.kcc20-reference');
    expect(patterns[12]?.status).toBe('scaffolded');
    expect(patterns[13]?.id).toBe('krc20.kcc20-ownable');
    expect(patterns[13]?.status).toBe('scaffolded');
    expect(patterns[14]?.id).toBe('krc20.kcc20-pausable');
    expect(patterns[14]?.status).toBe('scaffolded');
    expect(patterns[15]?.id).toBe('krc20.kcc20-capped');
    expect(patterns[15]?.status).toBe('scaffolded');
    expect(patterns[16]?.id).toBe('krc20.kcc20-vesting');
    expect(patterns[16]?.status).toBe('scaffolded');

    const privateAssetTransfer = patterns.find((pattern) => pattern.id === 'zk-aware.private-asset-transfer');
    expect(privateAssetTransfer?.status).toBe('scaffolded');
    expect(privateAssetTransfer?.contractPath).toBe('contracts/zk/private-asset-transfer.sil');
    expect(privateAssetTransfer?.compiler.requiresPatchedSilverc).toBe(true);
    expect(privateAssetTransfer?.compiler.bootstrapCommand).toBe('npm run patch:silverc:zk');
    expect(privateAssetTransfer?.verification.runtimeValidated).toBe(true);

    const compilePlan = buildPatternCompilePlan('zk-aware.private-asset-transfer');
    expect(compilePlan.pattern.id).toBe('zk-aware.private-asset-transfer');
    expect(compilePlan.spec.contractPath).toBe('contracts/zk/private-asset-transfer.sil');
    expect(compilePlan.spec.mode).toBe('compile');
    expect(compilePlan.bootstrapCommand).toBe('npm run patch:silverc:zk');
  });
});
