import { describe, expect, it } from 'vitest';
import { listPatterns } from '../sdk/src/index.js';

describe('pattern manifest scaffold', () => {
  it('exposes the first core entries and marks Ownable as scaffolded', () => {
    const patterns = listPatterns();
    expect(patterns.length).toBeGreaterThan(0);
    expect(patterns[0]?.id).toBe('core.ownable');
    expect(patterns[0]?.status).toBe('scaffolded');
    expect(patterns[0]?.contractPath).toBe('contracts/core/ownable.sil');
    expect(patterns[0]?.docPath).toBe('docs/patterns/core/ownable.md');
    expect(patterns[1]?.id).toBe('core.multisig');
    expect(patterns[1]?.status).toBe('scaffolded');
    expect(patterns[2]?.id).toBe('core.timelock');
    expect(patterns[2]?.status).toBe('scaffolded');
    expect(patterns[3]?.id).toBe('core.vault');
    expect(patterns[3]?.status).toBe('scaffolded');
    expect(patterns[4]?.id).toBe('core.escrow-bilateral');
    expect(patterns[4]?.status).toBe('scaffolded');
    expect(patterns[5]?.id).toBe('core.escrow-milestone');
    expect(patterns[5]?.status).toBe('scaffolded');
    expect(patterns[6]?.id).toBe('core.streaming-payment');
    expect(patterns[6]?.status).toBe('scaffolded');
    expect(patterns[7]?.id).toBe('core.vesting');
    expect(patterns[7]?.status).toBe('scaffolded');
    expect(patterns[8]?.id).toBe('core.dead-mans-switch');
    expect(patterns[8]?.status).toBe('scaffolded');
    expect(patterns[9]?.id).toBe('core.social-recovery');
    expect(patterns[9]?.status).toBe('scaffolded');
    expect(patterns[10]?.id).toBe('core.atomic-swap-htlc');
    expect(patterns[10]?.status).toBe('scaffolded');
    expect(patterns[11]?.id).toBe('core.freelance-payroll');
    expect(patterns[11]?.status).toBe('scaffolded');
    expect(patterns[12]?.id).toBe('krc20.kcc20-reference');
    expect(patterns[12]?.status).toBe('scaffolded');
    expect(patterns[13]?.id).toBe('krc20.kcc20-pausable');
    expect(patterns[13]?.status).toBe('scaffolded');
    expect(patterns[14]?.id).toBe('krc20.kcc20-capped');
    expect(patterns[14]?.status).toBe('scaffolded');
  });
});
