export type PatternPhase = 'core' | 'krc20' | 'zk-aware';

export interface PatternManifestEntry {
  id: string;
  title: string;
  phase: PatternPhase;
  stateful: boolean;
  status: 'planned' | 'scaffolded' | 'implemented' | 'audited';
  summary: string;
  contractPath?: string;
  docPath?: string;
}

export const patternManifest: PatternManifestEntry[] = [
  {
    id: 'core.ownable',
    title: 'Ownable',
    phase: 'core',
    stateful: true,
    status: 'scaffolded',
    summary: 'Single-owner covenant with explicit transfer semantics and KIP-20-safe state rotation.',
    contractPath: 'contracts/core/ownable.sil',
    docPath: 'docs/patterns/core/ownable.md',
  },
  {
    id: 'core.multisig',
    title: 'MultiSig',
    phase: 'core',
    stateful: true,
    status: 'scaffolded',
    summary: 'Configurable threshold policy over three explicit signers with a stateful reconfiguration path.',
    contractPath: 'contracts/core/multisig.sil',
    docPath: 'docs/patterns/core/multisig.md',
  },
  {
    id: 'core.timelock',
    title: 'TimeLock',
    phase: 'core',
    stateful: true,
    status: 'scaffolded',
    summary: 'Time-locked release scaffold with hard/soft cancel modes and a forward-only lock extension path.',
    contractPath: 'contracts/core/timelock.sil',
    docPath: 'docs/patterns/core/timelock.md',
  },
  {
    id: 'core.vault',
    title: 'Vault',
    phase: 'core',
    stateful: true,
    status: 'scaffolded',
    summary: 'Enterprise-treasury scaffold combining owner rotation, signer quorum, and timelocked release.',
    contractPath: 'contracts/core/vault.sil',
    docPath: 'docs/patterns/core/vault.md',
  },
  {
    id: 'core.escrow-bilateral',
    title: 'Escrow (bilateral)',
    phase: 'core',
    stateful: false,
    status: 'scaffolded',
    summary: 'Three-party bilateral escrow scaffold with arbiter-approved release/refund and buyer timeout reclaim.',
    contractPath: 'contracts/core/escrow-bilateral.sil',
    docPath: 'docs/patterns/core/escrow-bilateral.md',
  },
  {
    id: 'core.escrow-milestone',
    title: 'Escrow (milestone)',
    phase: 'core',
    stateful: true,
    status: 'scaffolded',
    summary: 'Stateful milestone escrow scaffold with monotonic progress, final release, dispute refund, and timeout reclaim.',
    contractPath: 'contracts/core/escrow-milestone.sil',
    docPath: 'docs/patterns/core/escrow-milestone.md',
  },
  {
    id: 'core.streaming-payment',
    title: 'Streaming Payment',
    phase: 'core',
    stateful: true,
    status: 'scaffolded',
    summary: 'Recurring-payment scaffold with recipient withdrawals, remaining allowance tracking, and sender cancellation.',
    contractPath: 'contracts/core/streaming-payment.sil',
    docPath: 'docs/patterns/core/streaming-payment.md',
  },
  {
    id: 'core.vesting',
    title: 'Vesting',
    phase: 'core',
    stateful: true,
    status: 'scaffolded',
    summary: 'Discrete-step vesting scaffold with cliff gating, claimed-amount tracking, and optional admin revocation.',
    contractPath: 'contracts/core/vesting.sil',
    docPath: 'docs/patterns/core/vesting.md',
  },
  {
    id: 'core.dead-mans-switch',
    title: "Dead Man's Switch",
    phase: 'core',
    stateful: true,
    status: 'scaffolded',
    summary: 'Inheritance/recovery scaffold with owner keepalive, fallback claim, and beneficiary rotation.',
    contractPath: 'contracts/core/dead-man-switch.sil',
    docPath: 'docs/patterns/core/dead-man-switch.md',
  },
  {
    id: 'core.social-recovery',
    title: 'Social Recovery',
    phase: 'core',
    stateful: true,
    status: 'scaffolded',
    summary: 'Guardian-quorum recovery scaffold with delayed activation and owner cancellation.',
    contractPath: 'contracts/core/social-recovery.sil',
    docPath: 'docs/patterns/core/social-recovery.md',
  },
  {
    id: 'core.atomic-swap-htlc',
    title: 'Atomic Swap (HTLC)',
    phase: 'core',
    stateful: false,
    status: 'scaffolded',
    summary: 'Hash time-locked contract scaffold with recipient claim and timeout refund paths.',
    contractPath: 'contracts/core/atomic-swap-htlc.sil',
    docPath: 'docs/patterns/core/atomic-swap-htlc.md',
  },
  {
    id: 'core.freelance-payroll',
    title: 'Freelance / Payroll',
    phase: 'core',
    stateful: false,
    status: 'scaffolded',
    summary: 'Client/worker/arbiter payment scaffold with mutual release, arbiter dispute paths, and timeout reclaim.',
    contractPath: 'contracts/core/freelance-payroll.sil',
    docPath: 'docs/patterns/core/freelance-payroll.md',
  },
  {
    id: 'krc20.kcc20-reference',
    title: 'KCC20 reference',
    phase: 'krc20',
    stateful: true,
    status: 'scaffolded',
    summary: 'Stable KCC20 asset contract with three ownership modes and non-minter supply-conservation invariants.',
    contractPath: 'contracts/tokens/kcc20.sil',
    docPath: 'docs/patterns/tokens/kcc20.md',
  },
  {
    id: 'krc20.kcc20-ownable',
    title: 'KCC20Ownable',
    phase: 'krc20',
    stateful: true,
    status: 'scaffolded',
    summary: 'Controller covenant that rotates KCC20 mint authority through an Ownable-style two-step admin handoff.',
    contractPath: 'contracts/tokens/kcc20-ownable.sil',
    docPath: 'docs/patterns/tokens/kcc20-ownable.md',
  },
  {
    id: 'krc20.kcc20-pausable',
    title: 'KCC20Pausable',
    phase: 'krc20',
    stateful: true,
    status: 'scaffolded',
    summary: 'Controller covenant that halts new KCC20 issuance while paused without freezing existing holder transfers.',
    contractPath: 'contracts/tokens/kcc20-pausable.sil',
    docPath: 'docs/patterns/tokens/kcc20-pausable.md',
  },
  {
    id: 'krc20.kcc20-capped',
    title: 'KCC20Capped',
    phase: 'krc20',
    stateful: true,
    status: 'scaffolded',
    summary: 'Controller covenant that caps KCC20 issuance through a decremented remaining-allowance state budget.',
    contractPath: 'contracts/tokens/kcc20-capped.sil',
    docPath: 'docs/patterns/tokens/kcc20-capped.md',
  },
  {
    id: 'krc20.kcc20-vesting',
    title: 'KCC20Vesting',
    phase: 'krc20',
    stateful: true,
    status: 'scaffolded',
    summary: 'Controller covenant that releases KCC20 issuance on a beneficiary-signed vesting schedule.',
    contractPath: 'contracts/tokens/kcc20-vesting.sil',
    docPath: 'docs/patterns/tokens/kcc20-vesting.md',
  },
];

export function listPatterns(): PatternManifestEntry[] {
  return [...patternManifest];
}
